steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
 
- script: 
    npm install
  displayName: 'npm install'
 
- script: 
    npm add react-is && npm run build
  displayName: 'npm build'
 
- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    sourceFolder: 'build' 
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

- powershell: |
   # Write your PowerShell commands here.
   Copy-Item "index.html" -Destination "200.html"
  workingDirectory: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy and rename index.html'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs: 
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: app

- task: PublishBuildArtifacts@1
  displayName: 'Publish ARM Template'
  inputs:
    PathtoPublish: 'pipelines/templates'
    ArtifactName: 'ARM'